### ISSUE TITLE
One step application of changes

### ISSUE THREAD

**Issue by zanodor** [publicus/obsidian-apply-patterns-plugin#62]
Sorry for ignoring the template, I would just have a question:  
Is there a way to apply a pattern in one step, e.g. using it with the Commander plugin or Obsidian Advanced URI? 

Use case:  
When applying changes to selection, one might need to use plugin 4-5 times on the same file (e.g. deleting some quotation marks but not all). In the current workflow (I am using iPad), one would need to invoke Command Pallette, select Apply Patterns/Selection and scroll down to Pattern on demand. 

The three steps could be shortened to one if the user could pin a command somewhere.  

Is what I want currently achieveable in some way or, if not, would you consider implementing a method to achieve it?  

Thank you for your time

Cheers

**Comment by jglev** [comment]
Thank you for reaching out. To confirm, it is possible to create Command Palette commands for single Patterns or groups of Patterns, using the "Commands" section of the Apply Patterns settings menu. Those can then be invoked with, e.g., the [QuickAdd plugin](https://github.com/chhoumann/quickadd), to pair them with other Command Palette commands in sequence.

Does that address your question?

**Comment by zanodor** [comment]
I have completely overlooked that setting. Thank you. This will make another plugin redundant (a favourite hobby of mine).  
Best

**Comment by jglev** [comment]
You're welcome! Thank you for asking!
